# Generated by Django 5.0 on 2024-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=80)),
                ('fecnac', models.DateField()),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
