# Generated by Django 5.0 on 2024-05-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=65, verbose_name='Apellido')),
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Mail')),
                ('contrasenna', models.CharField(max_length=700, verbose_name='Contrasenna')),
                ('fecnac', models.DateField(verbose_name='Fecha Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=120, verbose_name='Nro Pedido')),
                ('cant_prod', models.IntegerField(verbose_name='Cantidad Productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario')),
            ],
        ),
    ]
