# Generated by Django 5.0.6 on 2024-06-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
