# Generated by Django 5.0.6 on 2024-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_pedido_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preciod',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
