# Generated by Django 5.0.6 on 2024-06-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_product_precio_alter_product_preciod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=26),
        ),
    ]
