# Generated by Django 5.0.6 on 2024-06-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_product_precio_alter_product_preciod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preciod',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
