# Generated by Django 5.0.6 on 2024-06-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_product_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='product',
            name='preciod',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
