# Generated by Django 5.0.6 on 2024-06-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_categorias_alter_product_options_product_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
    ]
