# Generated by Django 5.0.6 on 2024-06-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_product_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
