# Generated by Django 5.0.6 on 2024-06-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_product_created_by_remove_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
