# Generated by Django 5.0.6 on 2024-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_categorias_product_created_by_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
