# Generated by Django 5.0.6 on 2024-06-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_review_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Product Reviews'},
        ),
    ]
