# Generated by Django 5.0.6 on 2024-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(default='Esto es un texto de descripcion base acerca de este gran producto, es perfecto para ti y se adecua a tu estilo', max_length=140),
        ),
    ]
