# Generated by Django 5.0.6 on 2024-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_product_redondeo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='redondeo',
        ),
        migrations.AlterField(
            model_name='product',
            name='preciod',
            field=models.DecimalField(decimal_places=3, max_digits=1000),
        ),
    ]
